<?php
session_start();


// RECEBE O $_POST
// vERIFICA
// PROCURA NO BANCO
// SE EXISTIR 
//    REGISTRA NA SESSION O EMAIL
//    DIRECIONA PARA O PERFIL.PHP
// SENÃO 
//    DIRECIONA PARA A PÁGINA ERROR_LOGIN.HTML
?>